USE sakila;

-- List the number of films per category.
SELECT COUNT(f.film_id) AS number_of_films, c.name AS category
FROM film AS f
LEFT JOIN film_category AS f_c
ON f.film_id = f_c.film_id
LEFT JOIN category AS c
ON f_c.category_id = c.category_id
GROUP BY c.name
;


-- Retrieve the store ID, city, and country for each store.
SELECT store.store_id, city.city, country.country
FROM store
LEFT JOIN address
ON store.address_id = address.address_id
LEFT JOIN city
ON address.city_id = city.city_id
LEFT JOIN country
ON city.country_id = country.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT store.store_id, SUM(payment.amount)
FROM store
LEFT JOIN staff
ON store.store_id = staff.store_id
LEFT JOIN payment
ON staff.staff_id = payment.staff_id
GROUP BY store_id;

-- Determine the average running time of films for each category.

SELECT category.name, AVG(film.length) AS avg_running_time
FROM film
LEFT JOIN film_category
ON film.film_id = film_category.film_id
LEFT JOIN category
ON film_category.category_id = category.category_id
GROUP BY category.name;

-- Identify the film categories with the longest average running time.

SELECT category.name, AVG(film.length) AS avg_running_time
FROM film
LEFT JOIN film_category
ON film.film_id = film_category.film_id
LEFT JOIN category
ON film_category.category_id = category.category_id
GROUP BY category.name
ORDER BY avg_running_time DESC;

-- Display the top 10 most frequently rented movies in descending order.

SELECT film.title, COUNT(rental.rental_id) AS rental_count
FROM rental
LEFT JOIN inventory 
ON rental.inventory_id = inventory.inventory_id
LEFT JOIN film 
ON inventory.film_id = film.film_id
GROUP BY film.film_id, film.title
ORDER BY rental_count DESC
LIMIT 10;
